### ISSUE TITLE
Missing success field

### ISSUE THREAD

**Issue by lorensr** [coinbase/coinbase-node#4]
When successfully calling this:

https://developers.coinbase.com/api#send-money

There should be a `success` field in the response. There isn't. Is the lib stripping it, or is it a bug in the API?

**Comment by jorilallo** [comment]
`coinbase-node` only returns the created transaction object when the `send_money` call is successful, otherwise `err` is returned instead of `data`. We're basically just abstracting the REST API here: 

https://github.com/coinbase/coinbase-node/blob/master/lib/model/AccountBase.js#L86

It's on our list to include pure code samples on the API reference but we just haven't gotten that far yet.

**Comment by lorensr** [comment]
Got it, thanks!
