### ISSUE TITLE
Error in createAddress: typo in the coinbase doc

### ISSUE THREAD

**Issue by manuel-di-iorio** [coinbase/coinbase-node#49]
This API call will throw the following error, both with sandbox mode and not:

    App\node_modules\coinbase\lib\errorHandler.js:55
    if (!callback) {throw "no callback - check method signature";}

Test code:

	client.getAccount('accountID', function(err, account) {
        if (err) return console.error(err);

		account.createAddress(function(err, address) { //the error is thrown here
			console.log(arguments); //debug
		});
	});
---
## Update:
I saw in the code that account.createAddress() requires the first argument to be `null` but your [doc](https://developers.coinbase.com/api/v2#create-address) shows a different code, so there is a little typo in the API reference

**Comment by maksim-s** [comment]
thanks for pointing this out. Fixed the docs

**Comment by befeltingu** [comment]
FYI this has not been fixed through out the docs. There are multiple places where the createAddress function is shown as taking a callback as the first argument

**Comment by prateektiwari7** [comment]
Hi @maksim-s 

Is the issue is resolved I dont think so .


var Client = require('coinbase').Client;

var client = new Client({'apiKey': 'xxxxxxxxxxxx',
                         'apiSecret': 'xxxxxxxxxxxxxxxxx'});

client.getAccount('64967ca1-cxxxxxxxxxx-xxxx-xxxxxx', function(err, account) {
     account.getAddresses(function(err, addresses) {
    console.log(addresses);
  });
});

Still getting the same error 
"  if (!callback) {throw "no callback - check method signature";}
                  ^
no callback - check method signature"

**Comment by basit1327** [comment]
i also getting the same error in createAddress and getAddresse function
is this issue is solved
