### ISSUE TITLE
getSpotPrice doesn't value parameter 'date'

### ISSUE THREAD

**Issue by ebeloded** [coinbase/coinbase-node#85]
According to Coinbase API v2 description (https://developers.coinbase.com/api/v2?shell#get-spot-price), **getSpotPrice** method can be supplied with `date` argument to fetch historic spot price. 

Current version of coinbase-node doesn't include `date` argument in its request to the API.

**Comment by jack-lewin** [comment]
I've had a look at this, and it seems like the problem is with the API itself, not coinbase-node.

If you change one of the tests to query a date, you'll see that it's definitely adding the parameter, and `GET https://api.coinbase.com/v2/prices/BTC-USD/sell?date=2017-01-01` returns the same with or without the date param.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
